#!/bin/sh

funcs="/etc/wpa_supplicant/functions.sh"

dpkg-divert --add --package libicd-network-wpasupplicant \
	--divert "${funcs}.dist" --rename "$funcs"

cp "${funcs}.dist" "$funcs"
sed '266s/$/ -u/' -i "$funcs"

exit 0
